services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: retro-chat-server-backend:dev
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  mongodb_data:
